bot:
  token: "token" # Discord Bot Token
  owners: [] # Discord User IDs of bot owners

keys:
  steam: "key" # Steam API Key
  faceit: "key" # FACEIT API Key

twitch:
  client_id: "key" # Twitch Client ID
  client_secret: "key" # Twitch Client Secret

locales:
  - name: "English" # Locale Name
    code: "en-US" # Locale Code
